version: '3.8'

services:
  mysql:
    image: mysql:8.0
    cap_add:
      - CAP_SYS_NICE
    container_name: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'pydatabase'
    ports:
      - 3306:3306
#    volumes:
#      - ./sql/database.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10