# Generated by Django 3.1.4 on 2021-01-27 13:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=140, validators=[django.core.validators.RegexValidator(re.compile('^[A-Z a-z]+$'), 'Nome de usuário Invalido, só pode haver letras', 'invalid')], verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-_]+$'), 'Nome de usuário Invalido, caracteres válidos: /@/./+/-/_', 'invalid')], verbose_name='Nome do Usuário'),
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Chave')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creiado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resets', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Nova senha',
                'verbose_name_plural': 'Novas senhas',
                'ordering': ['-created_at'],
            },
        ),
    ]
