# Generated by Django 3.1.4 on 2021-01-28 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210127_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordreset',
            options={'ordering': ['-created_at'], 'verbose_name': 'Nova Senha', 'verbose_name_plural': 'Novas Senhas'},
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='confirmed',
            field=models.BooleanField(blank=True, default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='key',
            field=models.CharField(max_length=100, unique=True, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='resets', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
